"""added note

Revision ID: 79becf1fdae1
Revises: b14ecf23c1b2
Create Date: 2026-10-01 15:04:26.794212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "79becf1fdae1"
down_revision: Union[str, Sequence[str], None] = "b14ecf23c1b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wanted_items",
        sa.Column(
            "craft",
            sa.String(length=15),
            server_default="Unassigned",
            nullable=False,
        ),
    )
    op.add_column(
        "wanted_items", sa.Column("note", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wanted_items", "note")
    op.drop_column("wanted_items", "craft")
    # ### end Alembic commands ###
