"""initial schema

Revision ID: b14ecf23c1b2
Revises:
Create Date: 2026-09-27 12:32:52.986722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b14ecf23c1b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_link", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("icon", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("rarity", sa.String(length=50), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("vendor_value", sa.Integer(), nullable=False),
        sa.Column("default_skin", sa.Integer(), nullable=True),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("game_types", sa.JSON(), nullable=False),
        sa.Column("restrictions", sa.JSON(), nullable=False),
        sa.Column("upgrade_into", sa.JSON(), nullable=True),
        sa.Column("upgrades_from", sa.JSON(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_table(
        "current_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created", sa.String(length=50), nullable=False),
        sa.Column("listing_type", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id"),
    )
    op.create_index(
        op.f("ix_current_transactions_item_id"),
        "current_transactions",
        ["item_id"],
        unique=False,
    )
    op.create_table(
        "historic_transactions",
        sa.Column("purchased", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created", sa.String(length=50), nullable=False),
        sa.Column("listing_type", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id"),
    )
    op.create_index(
        op.f("ix_historic_transactions_item_id"),
        "historic_transactions",
        ["item_id"],
        unique=False,
    )
    op.create_table(
        "wanted_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("target_quantity", sa.Integer(), nullable=False),
        sa.Column("listing_type", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wanted_items_user_id"),
        "wanted_items",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wanted_items_user_id"), table_name="wanted_items")
    op.drop_table("wanted_items")
    op.drop_index(
        op.f("ix_historic_transactions_item_id"),
        table_name="historic_transactions",
    )
    op.drop_table("historic_transactions")
    op.drop_index(
        op.f("ix_current_transactions_item_id"),
        table_name="current_transactions",
    )
    op.drop_table("current_transactions")
    op.drop_table("users")
    op.drop_table("items")
    # ### end Alembic commands ###
